-- =================================================================
-- SCRIPT DE MIGRACAO: AULAS DIGITAIS
-- =================================================================
--
-- INSTRUCOES:
-- 1. Copie todo o conteudo deste arquivo.
-- 2. Acesse o Painel do Supabase: https://supabase.com/dashboard/project/rgnzrcuredtbwcnnimta/sql
-- 3. Crie uma nova query, cole o codigo e clique em RUN.
--
-- =================================================================

-- 1. Criar tabela de aulas (se nao existir)
CREATE TABLE IF NOT EXISTS public.lessons (
    id TEXT PRIMARY KEY,
    titulo TEXT NOT NULL,
    area TEXT NOT NULL DEFAULT 'TEC_ENFERMAGEM',
    nivel TEXT NOT NULL DEFAULT 'intermedio',
    categoria TEXT,
    slides JSONB NOT NULL DEFAULT '[]'::jsonb,
    aula_conversacional JSONB,
    mini_quiz JSONB,
    flashcards JSONB,
    duracao_estimada_minutos INTEGER DEFAULT 30,
    versao TEXT DEFAULT '1.0.0',
    autor TEXT DEFAULT 'Sistema Angola Saude 2026',
    objectivo_geral TEXT,
    objectivos_especificos JSONB DEFAULT '[]'::jsonb,
    pre_requisitos JSONB DEFAULT '[]'::jsonb,
    tags JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Criar tabela de progresso do aluno (se nao existir)
CREATE TABLE IF NOT EXISTS public.lesson_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id TEXT REFERENCES public.lessons(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL, -- Pode ser UUID ou 'anonymous'
    progress_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    completed BOOLEAN DEFAULT FALSE,
    score INTEGER DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(lesson_id, user_id)
);

-- 3. Criar indices para performance
CREATE INDEX IF NOT EXISTS idx_lessons_area ON public.lessons(area);
CREATE INDEX IF NOT EXISTS idx_lessons_nivel ON public.lessons(nivel);
CREATE INDEX IF NOT EXISTS idx_lessons_created_at ON public.lessons(created_at DESC);

-- 4. Habilitar seguranca (RLS)
ALTER TABLE public.lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lesson_progress ENABLE ROW LEVEL SECURITY;

-- 5. Criar politicas de acesso (Permissiva para desenvolvimento)
-- Em producao, restringir INSERT/UPDATE/DELETE para admins

-- Politicas para lessons
DROP POLICY IF EXISTS "Public Read Lessons" ON public.lessons;
CREATE POLICY "Public Read Lessons" ON public.lessons FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Write Lessons" ON public.lessons;
CREATE POLICY "Public Write Lessons" ON public.lessons FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public Update Lessons" ON public.lessons;
CREATE POLICY "Public Update Lessons" ON public.lessons FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Public Delete Lessons" ON public.lessons;
CREATE POLICY "Public Delete Lessons" ON public.lessons FOR DELETE USING (true);

-- Politicas para lesson_progress
DROP POLICY IF EXISTS "Public All Progress" ON public.lesson_progress;
CREATE POLICY "Public All Progress" ON public.lesson_progress FOR ALL USING (true);

-- =================================================================
-- FIM DO SCRIPT
-- =================================================================
