-- Mais casos clínicos predefinidos (Parte 2)
-- Execute depois do primeiro arquivo

-- TÉCNICO DE FARMÁCIA
INSERT INTO game_cases (category_id, difficulty, case_data) VALUES
('TEC_FARMACIA', 4, '{"name": "José Roberto", "age": 72, "gender": "M", "avatar": "👴", "complaint": "Uso de vários medicamentos, dúvida sobre horários", "vitals": {"bp": "130/80", "hr": "70", "temp": "36.5", "spo2": "97"}, "disease": "Interação Medicamentosa", "options": ["Interação Medicamentosa", "Alergia Medicamentosa", "Superdosagem", "Subdosagem"], "questions": [{"text": "Quais medicamentos toma?", "answer": "Varfarina, AAS e ibuprofeno para dor", "clue": "Combinação de anticoagulante com AINEs"}, {"text": "Está sentindo algo diferente?", "answer": "Tenho tido sangramentos na gengiva", "clue": "Risco hemorrágico aumentado"}, {"text": "Quem receitou o ibuprofeno?", "answer": "Comprei na farmácia por conta", "clue": "Automedicação perigosa"}], "exams": {"prescricao": "Varfarina 5mg, AAS 100mg - prescritos", "interacoes": "GRAVE: AAS + Varfarina + AINE = risco hemorrágico", "alergias": "Sem alergias conhecidas", "adesao": "Irregular aos horários", "estoque": "Disponível"}, "treatment": "Orientar descontinuar ibuprofeno, encaminhar ao médico para ajuste", "conduct": "Alertar sobre interação, registrar ocorrência, orientar uso de paracetamol se dor", "explanation": "Varfarina + AAS já aumentam risco de sangramento. Adicionar ibuprofeno potencializa ainda mais."}'),

('TEC_FARMACIA', 3, '{"name": "Maria das Dores", "age": 65, "gender": "F", "avatar": "👵", "complaint": "Medicamento parece diferente do que costuma tomar", "vitals": {"bp": "140/90", "hr": "75", "temp": "36.4", "spo2": "98"}, "disease": "Troca de Medicamento", "options": ["Troca de Medicamento", "Medicamento Vencido", "Dose Inadequada", "Falsificação"], "questions": [{"text": "O que está diferente?", "answer": "A cor do comprimido mudou", "clue": "Possível troca de fabricante ou erro"}, {"text": "Verificou o nome na caixa?", "answer": "Está igual, mas o comprimido é diferente", "clue": "Pode ser genérico diferente"}, {"text": "Comprou onde?", "answer": "Na farmácia de sempre", "clue": "Fonte confiável"}], "exams": {"prescricao": "Atenolol 50mg", "interacoes": "Nenhuma identificada", "alergias": "Penicilina", "adesao": "Boa adesão", "estoque": "2 fabricantes disponíveis"}, "treatment": "Verificar lote, confirmar se é mesmo princípio ativo, orientar paciente", "conduct": "Comparar com medicamento anterior, confirmar com farmacêutico, tranquilizar paciente", "explanation": "Genéricos de fabricantes diferentes podem ter aparência diferente mantendo o mesmo princípio ativo."}'),

('TEC_FARMACIA', 5, '{"name": "Fernanda Costa", "age": 35, "gender": "F", "avatar": "👩", "complaint": "Manchas vermelhas após tomar antibiótico", "vitals": {"bp": "110/70", "hr": "90", "temp": "37.0", "spo2": "98"}, "disease": "Alergia Medicamentosa", "options": ["Alergia Medicamentosa", "Interação Medicamentosa", "Efeito Colateral", "Superdosagem"], "questions": [{"text": "Quando começou?", "answer": "30 minutos após tomar Amoxicilina", "clue": "Reação alérgica imediata"}, {"text": "Já teve alergia a medicamento?", "answer": "Nunca tomei antibiótico antes", "clue": "Primeira exposição às penicilinas"}, {"text": "Está com coceira?", "answer": "Muita, em todo o corpo", "clue": "Urticária generalizada"}], "exams": {"prescricao": "Amoxicilina 500mg 8/8h", "interacoes": "Nenhuma", "alergias": "NOVA: reação à Amoxicilina", "adesao": "Estava no 2º dia de tratamento", "estoque": "Alternativas disponíveis"}, "treatment": "Suspender Amoxicilina, registrar alergia, solicitar avaliação médica para alternativa", "conduct": "Orientar procurar hospital se piorar, NÃO dispensar penicilinas novamente, avisar médico", "explanation": "Urticária + prurido após antibiótico = reação alérgica. Deve-se registrar e evitar todo grupo das penicilinas."}');

-- ANÁLISES CLÍNICAS
INSERT INTO game_cases (category_id, difficulty, case_data) VALUES
('ANALISES_CLINICAS', 5, '{"name": "Cláudio Mendes", "age": 50, "gender": "M", "avatar": "👨", "complaint": "Exame de rotina, médico pediu check-up", "vitals": {"bp": "135/85", "hr": "78", "temp": "36.5", "spo2": "98"}, "disease": "Anemia Ferropriva", "options": ["Anemia Ferropriva", "Leucocitose", "Trombocitopenia", "Policitemia"], "questions": [{"text": "Tem se sentido cansado?", "answer": "Sim, muito cansaço e falta de ar", "clue": "Sintomas de anemia"}, {"text": "Sua alimentação é boa?", "answer": "Como pouca carne, sou quase vegetariano", "clue": "Baixa ingesta de ferro"}, {"text": "Notou sangramento?", "answer": "Não, mas fezes estão mais escuras", "clue": "Possível sangramento oculto"}], "exams": {"hemograma": "Hb: 9.5 g/dL, VCM: 68 fL, HCM: 24 pg - Anemia microcítica hipocrômica", "bioquimica": "Ferro sérico: 25 (baixo), Ferritina: 8 (baixa)", "urina": "Normal", "coagulacao": "Normal", "cultura": "Não indicada"}, "treatment": "Suplementação de ferro, investigar causa da perda", "conduct": "Liberar resultado com observação de anemia, orientar procurar médico", "explanation": "Hemoglobina baixa + VCM baixo + ferro e ferritina baixos = anemia ferropriva típica."}'),

('ANALISES_CLINICAS', 6, '{"name": "Patrícia Lima", "age": 28, "gender": "F", "avatar": "👩", "complaint": "Exame de urina para consulta ginecológica", "vitals": {"bp": "110/70", "hr": "72", "temp": "36.8", "spo2": "99"}, "disease": "Infecção Urinária", "options": ["Infecção Urinária", "Glomerulopatia", "Contaminação", "Diabetes"], "questions": [{"text": "Está com ardência ao urinar?", "answer": "Sim, há 3 dias, piora muito", "clue": "Disúria típica de ITU"}, {"text": "A urina está diferente?", "answer": "Mais escura e com cheiro forte", "clue": "Alterações características"}, {"text": "Tem febre?", "answer": "Não, só desconforto", "clue": "ITU baixa sem complicação"}], "exams": {"hemograma": "Leucócitos: 11.000 (leve aumento)", "bioquimica": "Normal", "urina": "Leucócitos: +++, Nitrito: positivo, Bactérias: ++, Hemácias: +", "coagulacao": "Normal", "cultura": "Encaminhada para cultura"}, "treatment": "Antibioticoterapia conforme antibiograma", "conduct": "Liberar EAS com urgência, orientar procurar médico, aguardar urocultura", "explanation": "Leucocitúria + nitrito positivo + bactérias + sintomas = infecção urinária bacteriana."}'),

('ANALISES_CLINICAS', 7, '{"name": "Osvaldo Gomes", "age": 60, "gender": "M", "avatar": "👴", "complaint": "Exames para controle de diabetes", "vitals": {"bp": "150/95", "hr": "80", "temp": "36.5", "spo2": "97"}, "disease": "Insuficiência Renal", "options": ["Insuficiência Renal", "Diabetes Descompensado", "Infecção", "Normal"], "questions": [{"text": "Como está o controle da glicemia?", "answer": "Não está muito bom, não sigo a dieta", "clue": "DM mal controlado"}, {"text": "Tem inchaço no corpo?", "answer": "Sim, pernas e rosto de manhã", "clue": "Edema por retenção hídrica"}, {"text": "Urina está espumando?", "answer": "Sim, bastante espuma", "clue": "Proteinúria"}], "exams": {"hemograma": "Hb: 10.8 (anemia leve), plaquetas normais", "bioquimica": "Creatinina: 3.2 (alta), Ureia: 85 (alta), Glicose: 210, K: 5.5 (limítrofe)", "urina": "Proteína: +++, cilindros hialinos", "coagulacao": "Normal", "cultura": "Não indicada"}, "treatment": "Encaminhamento para nefrologista urgente", "conduct": "Resultado crítico - comunicar médico imediatamente, valores alterados", "explanation": "Creatinina e ureia elevadas + proteinúria + anemia = insuficiência renal crônica, provavelmente nefropatia diabética."}');

-- Mais casos para TEC_ENFERMAGEM
INSERT INTO game_cases (category_id, difficulty, case_data) VALUES
('TEC_ENFERMAGEM', 5, '{"name": "Luciana Pereira", "age": 42, "gender": "F", "avatar": "👩", "complaint": "Febre de 39°C há 2 horas", "vitals": {"bp": "110/70", "hr": "110", "temp": "39.2", "spo2": "97"}, "disease": "Febre Alta", "options": ["Febre Alta", "Hipotermia", "Estado Normal", "Hipertermia Maligna"], "questions": [{"text": "Fez cirurgia recente?", "answer": "Sim, colecistectomia há 3 dias", "clue": "Risco de infecção pós-operatória"}, {"text": "A ferida está bem?", "answer": "Está um pouco vermelha e saindo líquido", "clue": "Sinais de infecção de sítio cirúrgico"}, {"text": "Tomou algo para febre?", "answer": "Não, estava esperando a enfermagem", "clue": "Aguardando conduta"}], "exams": {"sinaisVitais": "Febril, taquicárdica, normotensa", "glicemia": "95 mg/dL", "escalaGlasgow": "15", "escalaDor": "4/10 na ferida operatória", "balanco": "Normal"}, "treatment": "Antitérmico conforme prescrição, compressas, comunicar enfermeiro sobre ferida", "conduct": "Administrar Dipirona se prescrita, descobrir paciente, hidratar, comunicar alteração da FO", "explanation": "Febre alta no pós-operatório + ferida com sinais flogísticos sugere infecção. Exige avaliação."}'),

('TEC_ENFERMAGEM', 4, '{"name": "Raimundo Nonato", "age": 70, "gender": "M", "avatar": "👴", "complaint": "Não consegue engolir os comprimidos", "vitals": {"bp": "140/85", "hr": "72", "temp": "36.6", "spo2": "96"}, "disease": "Disfagia", "options": ["Disfagia", "Recusa Medicamentosa", "Confusão Mental", "Náusea"], "questions": [{"text": "Isso acontece sempre?", "answer": "Piorou depois do AVC há 6 meses", "clue": "Disfagia pós-AVC"}, {"text": "Consegue engolir líquidos?", "answer": "Com dificuldade, às vezes engasgo", "clue": "Risco de broncoaspiração"}, {"text": "Está alimentando bem?", "answer": "Pouco, tenho medo de engasgar", "clue": "Ingesta comprometida"}], "exams": {"sinaisVitais": "Estáveis", "glicemia": "120 mg/dL", "escalaGlasgow": "15", "escalaDor": "0/10", "balanco": "Ingesta reduzida"}, "treatment": "Avaliação de fono, verificar formas alternativas dos medicamentos", "conduct": "NÃO forçar via oral, comunicar enfermeiro, verificar se há formulação líquida", "explanation": "Disfagia pós-AVC requer avaliação de deglutição. Não administrar VO sem liberação de fono."}'),

('TEC_ENFERMAGEM', 6, '{"name": "Helena Santos", "age": 58, "gender": "F", "avatar": "👩", "complaint": "Curativo do cateter central está sujo de sangue", "vitals": {"bp": "125/80", "hr": "82", "temp": "36.8", "spo2": "98"}, "disease": "Risco de Infecção", "options": ["Risco de Infecção", "Sangramento Ativo", "Obstrução do Cateter", "Trombose"], "questions": [{"text": "Quando trocou o curativo?", "answer": "Há 5 dias, ninguém veio trocar", "clue": "Curativo vencido"}, {"text": "O local está doendo?", "answer": "Um pouco, e está quente", "clue": "Sinais de infecção local"}, {"text": "Saiu sangue pela punção?", "answer": "Não, parece que vazou", "clue": "Perda de integridade"}], "exams": {"sinaisVitais": "Estáveis, afebril", "glicemia": "110 mg/dL", "escalaGlasgow": "15", "escalaDor": "2/10 local", "balanco": "Normal"}, "treatment": "Trocar curativo com técnica asséptica, avaliar sinais de infecção", "conduct": "Comunicar enfermeiro, reunir material para troca, observar sinais flogísticos", "explanation": "Curativo de CVC deve ser trocado a cada 7 dias ou quando úmido/sujo. Calor local é sinal de alerta."}');

-- Verificar total final
SELECT category_id, COUNT(*) as total FROM game_cases GROUP BY category_id ORDER BY category_id;
