-- Casos Clínicos Pré-definidos para o Jogo Plantão de Emergência
-- Execute este SQL no Supabase SQL Editor

-- Primeiro, criar a tabela se não existir
CREATE TABLE IF NOT EXISTS game_cases (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    category_id TEXT NOT NULL,
    difficulty INTEGER DEFAULT 5,
    case_data JSONB NOT NULL,
    used BOOLEAN DEFAULT FALSE,
    used_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- CASOS PARA TÉCNICO DE ENFERMAGEM
INSERT INTO game_cases (category_id, difficulty, case_data) VALUES
('TEC_ENFERMAGEM', 3, '{"name": "Maria Santos", "age": 68, "gender": "F", "avatar": "👵", "complaint": "Tontura ao levantar e fraqueza nas pernas", "vitals": {"bp": "90/60", "hr": "98", "temp": "36.2", "spo2": "96"}, "disease": "Hipotensão Postural", "options": ["Hipotensão Postural", "Hipertensão Arterial", "Arritmia Cardíaca", "Desidratação Grave"], "questions": [{"text": "Quando começou a tontura?", "answer": "Sempre que levanto da cama ou cadeira", "clue": "Característica de hipotensão postural"}, {"text": "Está tomando algum medicamento?", "answer": "Sim, remédio para pressão alta", "clue": "Anti-hipertensivos podem causar hipotensão"}, {"text": "Bebeu água hoje?", "answer": "Pouca, não tenho sede", "clue": "Hidratação inadequada em idosos"}], "exams": {"sinaisVitais": "PA deitada: 120/80, PA em pé: 90/60 (queda significativa)", "glicemia": "95 mg/dL - Normal", "escalaGlasgow": "15 - Alerta e orientada", "escalaDor": "2/10 - Dor leve", "balanco": "Negativo - pouca ingestão hídrica"}, "treatment": "Orientar mudanças posturais lentas, aumentar hidratação, comunicar enfermeiro", "conduct": "Manter paciente deitada, elevar membros inferiores, oferecer líquidos", "explanation": "A queda de pressão ao mudar de posição, associada ao uso de anti-hipertensivos e baixa hidratação, indica hipotensão postural."}'),

('TEC_ENFERMAGEM', 4, '{"name": "João Ferreira", "age": 72, "gender": "M", "avatar": "👴", "complaint": "Sudorese fria e tremores", "vitals": {"bp": "110/70", "hr": "110", "temp": "36.0", "spo2": "98"}, "disease": "Hipoglicemia", "options": ["Hipoglicemia", "Infarto do Miocárdio", "Crise de Ansiedade", "Febre"], "questions": [{"text": "Tomou café da manhã hoje?", "answer": "Não, acordei atrasado para o exame", "clue": "Jejum prolongado pode causar hipoglicemia"}, {"text": "É diabético?", "answer": "Sim, tomo insulina de manhã", "clue": "Insulina sem alimentação = hipoglicemia"}, {"text": "Como está se sentindo agora?", "answer": "Confuso e com fome", "clue": "Sintomas clássicos de hipoglicemia"}], "exams": {"sinaisVitais": "Taquicardia, sudorese profusa, palidez", "glicemia": "48 mg/dL - BAIXA", "escalaGlasgow": "14 - Levemente confuso", "escalaDor": "0/10", "balanco": "Jejum prolongado"}, "treatment": "Administrar glicose oral ou IV conforme protocolo", "conduct": "Oferecer suco com açúcar imediatamente, monitorar glicemia a cada 15min", "explanation": "Paciente diabético em uso de insulina + jejum = hipoglicemia. Os sintomas de sudorese, tremores e confusão são característicos."}'),

('TEC_ENFERMAGEM', 5, '{"name": "Ana Luísa Mendes", "age": 45, "gender": "F", "avatar": "👩", "complaint": "Dificuldade para respirar e ansiedade", "vitals": {"bp": "140/90", "hr": "105", "temp": "36.5", "spo2": "91"}, "disease": "Oxigenação Inadequada", "options": ["Oxigenação Inadequada", "Ataque de Pânico", "Hipertensão", "Febre Alta"], "questions": [{"text": "Há quanto tempo está com falta de ar?", "answer": "Começou há 2 horas, piorando", "clue": "Progressão indica problema respiratório"}, {"text": "Tem alguma doença pulmonar?", "answer": "Sim, asma desde criança", "clue": "Histórico de doença respiratória"}, {"text": "Usou a bombinha hoje?", "answer": "Sim, mas não aliviou", "clue": "Broncoespasmo não controlado"}], "exams": {"sinaisVitais": "FR: 28 irpm, uso de musculatura acessória", "glicemia": "110 mg/dL - Normal", "escalaGlasgow": "15", "escalaDor": "3/10 - Desconforto torácico", "balanco": "Normal"}, "treatment": "Oxigenoterapia, nebulização conforme prescrição, posição Fowler", "conduct": "Elevar cabeceira, instalar O2 sob cateter nasal, chamar enfermeiro", "explanation": "Saturação de 91% indica hipoxemia. Paciente asmática em crise necessita de suporte de oxigênio imediato."}'),

('TEC_ENFERMAGEM', 3, '{"name": "Pedro Alves", "age": 82, "gender": "M", "avatar": "👴", "complaint": "Não consegue urinar há 12 horas", "vitals": {"bp": "150/95", "hr": "88", "temp": "37.2", "spo2": "97"}, "disease": "Retenção Urinária", "options": ["Retenção Urinária", "Infecção Urinária", "Insuficiência Renal", "Desidratação"], "questions": [{"text": "Sente dor na barriga?", "answer": "Sim, está muito inchada e dói", "clue": "Bexigoma palpável"}, {"text": "Tem problema de próstata?", "answer": "Sim, hiperplasia da próstata", "clue": "Causa comum de retenção em homens idosos"}, {"text": "Tentou urinar?", "answer": "Várias vezes, sai apenas gotas", "clue": "Obstrução do fluxo urinário"}], "exams": {"sinaisVitais": "Abdome distendido, globo vesical palpável", "glicemia": "105 mg/dL", "escalaGlasgow": "15", "escalaDor": "6/10 - Dor suprapúbica", "balanco": "Débito urinário: 0ml em 12h"}, "treatment": "Cateterismo vesical de alívio conforme prescrição médica", "conduct": "Comunicar enfermeiro, preparar material para sondagem, confortar paciente", "explanation": "Ausência de diurese + distensão abdominal + histórico de HPB indica retenção urinária aguda."}'),

('TEC_ENFERMAGEM', 4, '{"name": "Conceição Oliveira", "age": 78, "gender": "F", "avatar": "👵", "complaint": "Pele muito vermelha nas costas, não consegue deitar", "vitals": {"bp": "130/85", "hr": "78", "temp": "36.8", "spo2": "96"}, "disease": "Risco de Úlcera por Pressão", "options": ["Risco de Úlcera por Pressão", "Alergia de Contato", "Queimadura", "Infecção de Pele"], "questions": [{"text": "Há quanto tempo está acamada?", "answer": "5 dias, desde a cirurgia", "clue": "Imobilidade prolongada = risco de lesão"}, {"text": "Mudaram sua posição na cama?", "answer": "Poucas vezes, dói muito mexer", "clue": "Falta de mudança de decúbito"}, {"text": "A pele está íntegra?", "answer": "Está muito vermelha mas sem ferida", "clue": "Estágio 1 de lesão por pressão"}], "exams": {"sinaisVitais": "Estáveis", "glicemia": "98 mg/dL", "escalaBraden": "12 - Alto risco de lesão por pressão", "escalaDor": "5/10 na região sacral", "balanco": "Normal"}, "treatment": "Mudança de decúbito a cada 2h, colchão pneumático, hidratação da pele", "conduct": "Reposicionar paciente, aplicar AGE, comunicar enfermeiro para avaliação", "explanation": "Hiperemia em proeminência óssea + imobilidade + Braden baixo indica alto risco de úlcera por pressão."}');

-- CASOS PARA MÉDICO
INSERT INTO game_cases (category_id, difficulty, case_data) VALUES
('MEDICO', 5, '{"name": "Carlos Eduardo Silva", "age": 58, "gender": "M", "avatar": "👨", "complaint": "Dor forte no peito há 2 horas", "vitals": {"bp": "160/100", "hr": "95", "temp": "36.5", "spo2": "94"}, "disease": "Infarto Agudo do Miocárdio", "options": ["Infarto Agudo do Miocárdio", "Gastrite Aguda", "Pneumonia", "Costocondrite"], "questions": [{"text": "Como é a dor?", "answer": "Aperto no peito, irradiando para o braço esquerdo", "clue": "Padrão típico de dor anginosa"}, {"text": "Tem diabetes ou hipertensão?", "answer": "Sim, ambos há 10 anos", "clue": "Fatores de risco cardiovascular"}, {"text": "Já teve infarto antes?", "answer": "Não, mas meu pai morreu de infarto", "clue": "Histórico familiar positivo"}], "exams": {"hemograma": "Normal", "raiox": "Área cardíaca aumentada", "ecg": "Supradesnivelamento de ST em V1-V4", "usg": "Não indicado", "cultura": "Não indicado"}, "treatment": "AAS, Clopidogrel, Heparina, encaminhar para cateterismo", "conduct": "Monitorização contínua, acesso venoso, oxigênio, morfina se dor intensa", "explanation": "Dor precordial típica + alterações no ECG + fatores de risco confirmam IAM com supra de ST."}'),

('MEDICO', 6, '{"name": "Antônia Ferreira", "age": 34, "gender": "F", "avatar": "👩", "complaint": "Febre alta, tosse com catarro amarelo há 5 dias", "vitals": {"bp": "100/70", "hr": "110", "temp": "39.2", "spo2": "92"}, "disease": "Pneumonia Bacteriana", "options": ["Pneumonia Bacteriana", "Gripe Comum", "Tuberculose", "COVID-19"], "questions": [{"text": "A tosse é produtiva?", "answer": "Sim, muito catarro amarelo-esverdeado", "clue": "Expectoração purulenta sugere infecção bacteriana"}, {"text": "Sente dor ao respirar?", "answer": "Sim, do lado direito", "clue": "Dor pleurítica"}, {"text": "Tem falta de ar?", "answer": "Sim, piorou nos últimos 2 dias", "clue": "Comprometimento pulmonar progressivo"}], "exams": {"hemograma": "Leucocitose com desvio à esquerda (18.000)", "raiox": "Consolidação em lobo inferior direito", "ecg": "Taquicardia sinusal", "usg": "Não indicado", "cultura": "Colhida para análise"}, "treatment": "Antibioticoterapia empírica (Amoxicilina-Clavulanato), hidratação", "conduct": "Internação, oxigenoterapia, antitérmicos, monitorização", "explanation": "Febre alta + tosse produtiva + consolidação ao RX + leucocitose = pneumonia bacteriana."}'),

('MEDICO', 7, '{"name": "Roberto Nascimento", "age": 62, "gender": "M", "avatar": "👴", "complaint": "Fraqueza súbita no lado direito do corpo", "vitals": {"bp": "180/110", "hr": "88", "temp": "36.6", "spo2": "97"}, "disease": "Acidente Vascular Cerebral", "options": ["Acidente Vascular Cerebral", "Enxaqueca", "Epilepsia", "Hipoglicemia"], "questions": [{"text": "Quando começaram os sintomas?", "answer": "Há 1 hora, durante o almoço", "clue": "Início súbito é característico de AVC"}, {"text": "Consegue levantar os dois braços?", "answer": "Não, o direito não levanta", "clue": "Hemiparesia"}, {"text": "A fala está normal?", "answer": "Está enrolada, difícil entender", "clue": "Disartria"}], "exams": {"hemograma": "Normal", "raiox": "Não indicado", "ecg": "Fibrilação atrial", "usg": "Não indicado", "cultura": "Não indicado"}, "treatment": "Tomografia de crânio urgente, avaliar trombólise se AVC isquêmico", "conduct": "Estabilização, monitorização, glicemia, NIH Stroke Scale", "explanation": "Déficit motor súbito + alteração de fala + FA = AVC provável. Tempo é crucial (janela para trombólise)."}'),

('MEDICO', 5, '{"name": "Laura Beatriz", "age": 28, "gender": "F", "avatar": "👩", "complaint": "Dor abdominal intensa no lado direito inferior", "vitals": {"bp": "120/80", "hr": "100", "temp": "38.0", "spo2": "98"}, "disease": "Apendicite Aguda", "options": ["Apendicite Aguda", "Cólica Menstrual", "Infecção Urinária", "Gastroenterite"], "questions": [{"text": "Onde a dor começou?", "answer": "Primeiro na região do umbigo, depois desceu", "clue": "Migração típica da dor apendicular"}, {"text": "Tem náuseas ou vômitos?", "answer": "Sim, vomitei 2 vezes", "clue": "Sintomas associados comuns"}, {"text": "Quando foi a última menstruação?", "answer": "Há 10 dias, normal", "clue": "Descarta causas ginecológicas"}], "exams": {"hemograma": "Leucocitose (14.000)", "raiox": "Inespecífico", "ecg": "Normal", "usg": "Apêndice de 12mm, espessado, líquido periapendicular", "cultura": "Não indicado"}, "treatment": "Apendicectomia de urgência", "conduct": "Jejum, hidratação, analgesia, antibiótico profilático, preparar cirurgia", "explanation": "Dor que migrou para FID + febre + leucocitose + USG alterada = apendicite aguda."}'),

('MEDICO', 6, '{"name": "Marcos Antônio", "age": 55, "gender": "M", "avatar": "👨", "complaint": "Muita sede, urinando muito e perdendo peso", "vitals": {"bp": "130/85", "hr": "92", "temp": "36.8", "spo2": "98"}, "disease": "Cetoacidose Diabética", "options": ["Cetoacidose Diabética", "Diabetes Insipidus", "Infecção Urinária", "Hipertireoidismo"], "questions": [{"text": "É diabético conhecido?", "answer": "Descobri há 3 meses, não tomei o remédio direito", "clue": "Má adesão ao tratamento"}, {"text": "Sente hálito diferente?", "answer": "Minha esposa disse que está com cheiro de fruta", "clue": "Hálito cetônico"}, {"text": "Está confuso ou sonolento?", "answer": "Um pouco tonto, mas acordado", "clue": "Alteração do sensório leve"}], "exams": {"hemograma": "Hemoconcentração", "raiox": "Normal", "ecg": "Normal", "usg": "Normal", "cultura": "Não indicado"}, "treatment": "Insulina regular IV, hidratação vigorosa, correção de potássio", "conduct": "UTI, monitorização contínua, gasometria seriada, controle glicêmico horário", "explanation": "Poliúria, polidipsia, perda de peso + hálito cetônico + diabético sem tratamento = CAD."}');

-- CASOS PARA ENFERMAGEM (Licenciatura)
INSERT INTO game_cases (category_id, difficulty, case_data) VALUES
('ENFERMAGEM', 5, '{"name": "Josefa Maria", "age": 75, "gender": "F", "avatar": "👵", "complaint": "Não consegue respirar deitada, precisa de vários travesseiros", "vitals": {"bp": "150/95", "hr": "102", "temp": "36.4", "spo2": "89"}, "disease": "Padrão Respiratório Ineficaz", "options": ["Padrão Respiratório Ineficaz", "Débito Cardíaco Diminuído", "Ansiedade", "Troca de Gases Prejudicada"], "questions": [{"text": "Há quanto tempo está assim?", "answer": "Piorou nos últimos 3 dias", "clue": "Descompensação progressiva"}, {"text": "Tem doença do coração?", "answer": "Sim, insuficiência cardíaca", "clue": "IC descompensada causa ortopneia"}, {"text": "Os pés estão inchados?", "answer": "Muito, não cabem nos sapatos", "clue": "Edema de membros inferiores"}], "exams": {"anamnese": "Ortopneia + dispneia paroxística noturna relatada", "exameFisico": "Estertores em bases, edema ++/4+, turgência jugular", "escalaBraden": "16 - Risco moderado", "escalaFugulin": "Intermediário", "historicoFamiliar": "Mãe faleceu de AVC"}, "treatment": "Implementar SAE completa, posicionamento Fowler alto, balanço hídrico rigoroso", "conduct": "Prescrição de enfermagem: restrição hídrica, monitorar sinais de piora, oximetria contínua", "explanation": "Ortopneia + estertores + edema indicam congestão pulmonar. Diagnóstico: Padrão respiratório ineficaz relacionado à congestão."}'),

('ENFERMAGEM', 4, '{"name": "Severino José", "age": 68, "gender": "M", "avatar": "👴", "complaint": "Inchaço generalizado e não está urinando bem", "vitals": {"bp": "170/100", "hr": "78", "temp": "36.5", "spo2": "94"}, "disease": "Débito Cardíaco Diminuído", "options": ["Débito Cardíaco Diminuído", "Excesso de Volume de Líquidos", "Perfusão Tissular Ineficaz", "Intolerância à Atividade"], "questions": [{"text": "Sente cansaço ao caminhar?", "answer": "Não consigo andar nem até o banheiro", "clue": "Intolerância ao esforço severa"}, {"text": "Quanto está urinando por dia?", "answer": "Muito pouco, às vezes nada", "clue": "Oligúria por baixo débito renal"}, {"text": "Acorda à noite para urinar?", "answer": "Sim, 3-4 vezes, mas sai pouco", "clue": "Redistribuição noturna de líquidos"}], "exams": {"anamnese": "Cardiopatia prévia, em uso de Furosemida e Carvedilol", "exameFisico": "Anasarca, B3 audível, hepatomegalia", "escalaBraden": "14 - Alto risco", "escalaFugulin": "Alta dependência", "historicoFamiliar": "Irmão com IC"}, "treatment": "Plano de cuidados: monitorização hemodinâmica, controle de peso diário, educação sobre restrição sódio", "conduct": "Avaliar débito urinário, pesar diariamente, registrar ingesta e excreta", "explanation": "Edema + oligúria + intolerância ao esforço + B3 = sinais de IC. Diagnóstico NANDA: Débito cardíaco diminuído."}'),

('ENFERMAGEM', 5, '{"name": "Iracema Souza", "age": 80, "gender": "F", "avatar": "👵", "complaint": "Caiu em casa ontem, está confusa desde então", "vitals": {"bp": "100/65", "hr": "68", "temp": "35.8", "spo2": "95"}, "disease": "Confusão Aguda", "options": ["Confusão Aguda", "Demência", "Risco de Quedas", "Mobilidade Prejudicada"], "questions": [{"text": "Ela estava confusa antes da queda?", "answer": "Não, era bem lúcida até ontem", "clue": "Mudança aguda do estado mental"}, {"text": "Está tomando medicamentos novos?", "answer": "Começou remédio para dormir há 3 dias", "clue": "Benzodiazepínicos podem causar confusão em idosos"}, {"text": "Quando bebeu água pela última vez?", "answer": "Não sabemos, ela não pedia", "clue": "Desidratação em idosos"}], "exams": {"anamnese": "Uso de Clonazepam recente, pouca ingesta oral", "exameFisico": "Desorientada em tempo e espaço, pele seca, turgor diminuído", "escalaBraden": "12 - Alto risco", "escalaFugulin": "Alta dependência", "historicoFamiliar": "Sem histórico de demência"}, "treatment": "Investigar causas reversíveis (medicamentos, desidratação, infecção), reorientação", "conduct": "CAM para delirium, hidratação, rever medicações, orientar familiares", "explanation": "Confusão de início agudo + uso de sedativo + desidratação = Delirium/Confusão aguda, diferente de demência."}');

-- Adicionar mais 5 casos para ter variedade
INSERT INTO game_cases (category_id, difficulty, case_data) VALUES
('TEC_ENFERMAGEM', 5, '{"name": "Francisco Soares", "age": 55, "gender": "M", "avatar": "👨", "complaint": "Vômitos persistentes e dor abdominal", "vitals": {"bp": "100/60", "hr": "115", "temp": "37.5", "spo2": "97"}, "disease": "Desidratação", "options": ["Desidratação", "Apendicite", "Gastrite", "Intoxicação Alimentar"], "questions": [{"text": "Há quanto tempo está vomitando?", "answer": "Desde ontem à noite, já perdi a conta", "clue": "Perdas volémicas importantes"}, {"text": "Conseguiu beber água?", "answer": "Não, vomito tudo que tento beber", "clue": "Incapacidade de reposição oral"}, {"text": "Sua boca está seca?", "answer": "Muito, a língua parece papel", "clue": "Sinal de desidratação"}], "exams": {"sinaisVitais": "Hipotensão, taquicardia compensatória", "glicemia": "85 mg/dL", "escalaGlasgow": "15", "escalaDor": "5/10 abdominal", "balanco": "Negativo, perdas importantes"}, "treatment": "Hidratação IV, antieméticos, reposição eletrolítica", "conduct": "Puncionar acesso calibroso, iniciar SF 0,9% conforme prescrição, monitorar diurese", "explanation": "Vômitos persistentes + mucosas secas + taquicardia + hipotensão = desidratação moderada a grave."}'),

('TEC_ENFERMAGEM', 4, '{"name": "Regina Celia", "age": 62, "gender": "F", "avatar": "👩", "complaint": "Está muito agitada, tentando arrancar o soro", "vitals": {"bp": "145/90", "hr": "105", "temp": "36.8", "spo2": "96"}, "disease": "Agitação Psicomotora", "options": ["Agitação Psicomotora", "Ansiedade", "Hipóxia", "Dor Não Controlada"], "questions": [{"text": "Ela está orientada?", "answer": "Não sabe onde está, fala coisas sem sentido", "clue": "Desorientação associada"}, {"text": "Quando começou a agitação?", "answer": "Há 2 horas, estava calma antes", "clue": "Mudança aguda de comportamento"}, {"text": "Dormiu bem à noite?", "answer": "Não, passou a noite toda acordada", "clue": "Privação de sono pode contribuir"}], "exams": {"sinaisVitais": "Taquicárdica, agitada", "glicemia": "180 mg/dL - Elevada", "escalaGlasgow": "13 - Confusa", "escalaDor": "Não é possível avaliar adequadamente", "balanco": "Normal"}, "treatment": "Descartar causas orgânicas, contenção se necessário, medicação conforme prescrição", "conduct": "Falar calmamente, ambiente tranquilo, grades elevadas, chamar enfermeiro", "explanation": "Agitação súbita + desorientação pode ser delirium. Importante descartar hipóxia, dor ou alteração metabólica."}'),

('MEDICO', 6, '{"name": "Antônio Carlos", "age": 48, "gender": "M", "avatar": "👨", "complaint": "Dor intensa nas costas que irradia para a barriga", "vitals": {"bp": "170/100", "hr": "108", "temp": "36.5", "spo2": "98"}, "disease": "Cólica Nefrética", "options": ["Cólica Nefrética", "Lombalgia Mecânica", "Pancreatite", "Aneurisma de Aorta"], "questions": [{"text": "A dor melhora em alguma posição?", "answer": "Não consigo ficar parado, preciso andar", "clue": "Inquietação típica de cólica renal"}, {"text": "Notou sangue na urina?", "answer": "Sim, está mais escura e vermelha", "clue": "Hematúria por trauma do cálculo"}, {"text": "Já teve pedra nos rins?", "answer": "Sim, há 5 anos atrás", "clue": "Histórico de litíase renal"}], "exams": {"hemograma": "Normal", "raiox": "Calcificação em trajeto ureteral esquerdo", "ecg": "Taquicardia sinusal", "usg": "Hidronefrose grau II à esquerda, cálculo de 6mm em JUV", "cultura": "Não indicado"}, "treatment": "Analgesia potente (Tramadol/Morfina), AINE, hidratação, avaliar expulsão vs intervenção", "conduct": "Analgesia imediata, colher exames, avaliar necessidade de internação", "explanation": "Dor em cólica + irradiação típica + hematúria + USG com cálculo = nefrolitíase em migração."}');

-- Verificar quantos casos foram inseridos
SELECT category_id, COUNT(*) as total FROM game_cases GROUP BY category_id;
